# creating notification deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
      - name: notification-api
        image: registry.deti:5000/egs-doctalk/egs-notification-svc:v1
        ports:
        - containerPort: 3030

# creating notification service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: egs-doctalk
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: ClusterIP

  # Configure Traefik ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-webapp-k3s
  namespace: egs-doctalk
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-egs-doctalk-noti.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notification-svc
            port: 
              number: 80


